### ISSUE TITLE
NullPointerException in SumUpAPI.openPaymentActivity

### ISSUE THREAD

**Issue by mhagmajer** [sumup/sumup-android-sdk#10]
I'm getting the error below when running `SumUpAPI.openPaymentActivity(myActivity, payment, SUMUP);`. My activity derives from `android.app.Acitivity` for which `getSupportActionBar()` in the implementation of `com.sumup.merchant.ui.Activities.SumUpBaseActivity.setUpActionBar` returns null, hence the exception.

```js
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
                                                     at com.sumup.merchant.ui.Activities.SumUpBaseActivity.setUpActionBar(SourceFile:54)
                                                     at com.sumup.merchant.ui.Activities.SumUpBaseActivity.onCreate(SourceFile:29)
                                                     at com.sumup.merchant.api.LoadSumUpPaymentsActivity.onCreate(SourceFile:66)
                                                     at android.app.Activity.performCreate(Activity.java:6876)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                     at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:158) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
```

Tested on Android 6.0.1.

**Comment by ultrah** [comment]
Which minSDKVersion and targetSDKVersion do you use?

**Comment by mhagmajer** [comment]
Thanks for your reply. This is the build config that we're using:

```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.mysumupapp"
        minSdkVersion 16
        targetSdkVersion 22
    }
```

**Comment by ultrah** [comment]
Thanks! We'll have a look and try to reproduce

**Comment by mhagmajer** [comment]
Awesome! My guess is that the `SumUpBaseActivity.setUpActionBar` should account for `getSupportActionBar` returning null since according to the Android API this is possible that the activity does not have action bar.

**Comment by mhagmajer** [comment]
@ultrah, any news here?

**Comment by ultrah** [comment]
Looks like this one got lost in the backlog. I just did a clean build of the sample app with the parameters you supplied but I could not reproduce the issue. Are you sure you have `transitive = true` enabled for the SumUp dependency?

**Comment by mhagmajer** [comment]
@ultrah, I created a repository with a simplistic project that produces the exception mentioned: https://github.com/mhagmajer/sumup-android-sdk-example

**Comment by ultrah** [comment]
Thanks, I can reproduce with this sample app! When I switch to `com.sumup:merchant-sdk:1.61.0-SNAPSHOT` it works for me. Can you confirm?

You need to add  `maven { url 'https://maven.sumup.com/snapshots' }` to your dependencies to use it.

**Comment by mhagmajer** [comment]
Works, thanks!

**Comment by ultrah** [comment]
Great :) Please don't use snapshots for production builds though, they are not tested. We will do a new release soon-ish.
