### ISSUE TITLE
Crash when denying Device Location permission

### ISSUE THREAD

**Issue by Milszym** [sumup/sumup-android-sdk#122]
When I am using sumup-android-sdk to allow user to login there is a permission request popup. When I click Deny on `Allow App to access this device's location?` permission request popup then the app is crashing.

<img width="853" alt="Screenshot 2020-06-10 at 11 31 23" src="https://user-images.githubusercontent.com/12632186/84251772-15b07880-ab0e-11ea-9d6a-cc0b2735dc85.png">

I am using this code to open SumUp login activity:
```
val sumUpLogin = SumUpLogin.builder(sumUpAffiliateKey)
            .accessToken(accessToken)
            .build()

SumUpAPI.openLoginActivity(
            this, sumUpLogin,
            SUMUP_AUTH_REQUEST_CODE
)
```

Where SUMUP_AUTH_REQUEST_CODE is just activity result code, sumUpAffiliateKey is a key taken from SumUp web developer panel and accessToken is a token retrieved via authorization flow available here: https://developer.sumup.com/docs/authorization/

The error I am receiving after I click deny is:
`2020-06-10 11:10:27.763 23160-23160/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: *.*.*.*, PID: 23160
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {*.*.*.*/com.sumup.merchant.ui.Activities.LoginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4614)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4656)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7072)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.sumup.merchant.api.LoadSumUpPaymentsActivity.createAffiliateResponseIntent(SourceFile:473)
        at com.sumup.merchant.api.LoadSumUpPaymentsActivity.sendAffiliateResponse(SourceFile:577)
        at com.sumup.merchant.ui.Activities.LoginActivity.onRequestPermissionsResult(SourceFile:286)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7941)
        at android.app.Activity.dispatchActivityResult(Activity.java:7763)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4607)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4656) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7072)`

Instead of crash I would rather expect that the SDK will show proper message to the user, something like "You can't login if you won't accept permission".

**Comment by Mike-Lopez** [comment]
Hi,

Please provide SDK version, device model, android version?

Best

**Comment by danielebart** [comment]
Same here, we are receiving this crash on several phone brands and Android API levels.

**Comment by Milszym** [comment]
> Hi,
> 
> Please provide SDK version, device model, android version?
> 
> Best

I was using Samsung Tab A 10 2019 with SDK 28, Android Version 9.0
SumUp SDK Version: 3.2.2

**Comment by Milszym** [comment]
@Mike-Lopez Is there some progress on this matter? It's really bad user experience when the app crashes.

**Comment by carlaf92** [comment]
We are still facing this issue. Any update?
