### ISSUE TITLE
App Crashes when selecting Phone intent

### ISSUE THREAD

**Issue by vladaman** [sumup/sumup-android-sdk#128]
On some devices there is no app to handle intent tel:xxxxx - SumUp should not make assumption that the Phone functionality exists.

```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.DIAL dat=tel:xxxxxxxxxxxxx }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
       at android.app.Activity.startActivityForResult(Activity.java:3968)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
       at android.app.Activity.startActivityForResult(Activity.java:3920)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
       at com.sumup.merchant.ui.Activities.SumUpBaseActivity.startActivityForResult(SumUpBaseActivity.java:103)
       at android.app.Activity.startActivity(Activity.java:4259)
       at android.app.Activity.startActivity(Activity.java:4227)
       at com.sumup.merchant.ui.Activities.SumUpBaseActivity.startActivity(SumUpBaseActivity.java:97)
       at com.sumup.merchant.util.OSUtils.startIntentDialSupportAction(OSUtils.java:98)
       at com.sumup.merchant.ui.Fragments.PinPlusBtMoreHelpFragment.handleRightButtonClick(PinPlusBtMoreHelpFragment.java:98)
       at com.sumup.merchant.ui.Fragments.SetupFragment$2.onClick(SetupFragment.java:87)
       at android.view.View.performClick(View.java:5265)
       at android.view.View$PerformClick.run(View.java:21534)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by babyboy123** [comment]
I have the same problem. I can't locate it. Have you solved it?

**Comment by leila-sumup** [comment]
Hello, thanks for taking the time to report this, and apologies the slow follow-up on our end.

We were assuming a dialer app is always available, which obviously isn't the case on all Android devices.

Since this is a few years old, we'd like to check if it's still relevant before moving forward. Could you confirm:
-Are you still seeing this with the latest version of the SDK?
-If so, what device and Android version?
Any steps to reproduce would be helpful.

If it's no longer an issue, we'll go ahead and close this out, but we'll keep the underlying concern noted for future improvements.

Thanks again for your patience.

**Comment by leila-sumup** [comment]
Closing this one as it seems no longer relevant and no recent follow up. 

If this issue still persists with the latest SDK, please re-open the issue and provide steps to reproduce and information on your setup (card reader used, mobile device manufacturer and model) so that we can look into it!
