### ISSUE TITLE
Problem with SDK integration

### ISSUE THREAD

**Issue by Jacksotnik** [sumup/sumup-android-sdk#14]
Hello, i'm trying to integrate SumUp SDK into my Android application and i have some problems with it.
So i'm copying everything from sample application, SumUp activity is opening, asking card, money charged from my bank card but after that application is crash and i don't have any activity result. 
Here is the error text:
```
E/UncaughtException: java.lang.NoSuchFieldError: No static field receipt_input_layout of type I in class Lcom/sumup/merchant/R$id; or its superclasses (declaration of 'com.sumup.merchant.R$id' appears in /data/data/com.hssoft.cashassistmobile/files/instant-run/dex/slice-slice_5-classes.dex)
                         at com.sumup.merchant.ui.Fragments.ReceiptFragment.setUpDefaultUiState(SourceFile:186)
                         at com.sumup.merchant.ui.Fragments.ReceiptFragment.onActivityCreated(SourceFile:153)
                         at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2089)
                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1133)
                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                         at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
                         at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:536)
                         at android.os.Handler.handleCallback(Handler.java:739)
                         at android.os.Handler.dispatchMessage(Handler.java:95)
                         at android.os.Looper.loop(Looper.java:148)
                         at android.app.ActivityThread.main(ActivityThread.java:7329)
                         at java.lang.reflect.Method.invoke(Native Method)
                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by ultrah** [comment]
Do you have a layout file name `fragment_receipt.xml` in your project?

**Comment by Jacksotnik** [comment]
Yes

**Comment by ultrah** [comment]
There is a naming conflict, you will need to rename it to get the SDK to work.

**Comment by Jacksotnik** [comment]
))))) Thank's. I will try

**Comment by ultrah** [comment]
Glad to help. We will discuss it it makes sense to prefix our layout files in the future to avoid this kind of situation.

**Comment by ultrah** [comment]
Did it work?

**Comment by Jacksotnik** [comment]
Yes. thank's for help) 

    пятница, 28 октября 2016 15:20 Philipp Ebert <notifications@github.com> писал(а):
 

 Did it work? —
