### ISSUE TITLE
Crash in ReadCardFragment.java:220 in v3.2.2 (since Sep 02, 2020)

### ISSUE THREAD

**Issue by christxph** [sumup/sumup-android-sdk#142]
We have been receiving a lot of crash reports related to the SumUp SDK. This started happening on Sep 02, 2020 without an app or SDK update (currently using 3.2.2)

Stacktrace:
```
Fatal Exception: java.lang.IllegalStateException: readerType can not be null
       at com.sumup.merchant.ui.Fragments.ReadCardFragment.initReaderImages(ReadCardFragment.java:220)
       at com.sumup.merchant.ui.Fragments.ReadCardFragment.onCreateView(ReadCardFragment.java:168)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
       at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
       at android.app.Activity.performStart(Activity.java:7980)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3646)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8107)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by LaylaSD** [comment]
We have integrated SumUp with our own POS app and have also seen this issue.

**Comment by HeyPouya** [comment]
Hi @christxph and @LaylaSD, are you still experiencing this issue with the latest version of the SDK?

**Comment by leila-sumup** [comment]
Closing this one for lack of movement, please feel free to reopen this ticket with context on how to reproduce this if this still presents an issue for you!
