### ISSUE TITLE
App crashes in com.sumup.merchant.reader.troubleshooting.ui.PinPlusBtToggleFragment

### ISSUE THREAD

**Issue by javierperezrico** [sumup/sumup-android-sdk#156]
Hi 👋, first time here

Sometimes we are getting a runtime exception using the 3.3.0 sdk version. 

Here is the stacktrace logged in our crashlitics:

```
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.bluetooth.adapter.action.STATE_CHANGED flg=0x15000010 (has extras) } in com.sumup.merchant.reader.helpers.BluetoothStateChangeHelper$1@5e67a9c
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_58300(LoadedApk.java:1448)
       at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.$m$0(-.java:4)
       at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.run(-.java)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by java.lang.IllegalArgumentException: View=DecorView@ced9f64[] not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:520)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:413)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:206)
       at android.app.Dialog.dismissDialog(Dialog.java:495)
       at android.app.Dialog.dismiss(Dialog.java:478)
       at com.sumup.merchant.reader.troubleshooting.ui.PinPlusBtToggleFragment$2.onComplete(PinPlusBtToggleFragment.java:120)
       at com.sumup.merchant.reader.helpers.BluetoothStateChangeHelper$1.onReceive(BluetoothStateChangeHelper.java:63)
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_58300(LoadedApk.java:1435)
       at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.$m$0(-.java:4)
       at android.app.-$Lambda$FilBqgnXJrN9Mgyks1XHeAxzSTk.run(-.java)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

We see this crash also at andorid 8 and 10 devices

**Comment by leila-sumup** [comment]
Hello, thanks for taking the time to report this, and apologies the slow follow-up on our end.

Since this is a few years old, we'd like to check if it's still relevant before moving forward.
Could you confirm:
-Are you still seeing this with the latest version of the SDK?
-If so, what mobile device do you use, and what Android version?
-Is there any way to reliably reproduce it or trends in occurrence?

If it's no longer an issue, we'll go ahead and close this out, but we'll keep the underlying concern noted for future improvements.

Thanks again for your patience.

**Comment by leila-sumup** [comment]
Closing this one as it seems no longer relevant and no recent follow up.

If this issue still persists with the latest SDK, please re-open the issue and provide steps to reproduce and information on your setup (card reader used, mobile device manufacturer and model) so that we can look into it!
