### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by fred4o** [sumup/sumup-android-sdk#163]
my App is killed sometimes when i use
  SumUpLogin sumupLogin = SumUpLogin.builder(Constants.SUM_UP_AFFILIATE_KEY).build();
        SumUpAPI.openLoginActivity(MainActivity.this, sumupLogin, 1);
with this error.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: bg.hippotaxi.driver, PID: 6956
    java.lang.RuntimeException: Unable to start activity ComponentInfo{bg.hippotaxi.driver/com.sumup.merchant.reader.identitylib.ui.activities.LoginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.sumup.merchant.reader.ReaderModuleCoreState.inject(java.lang.Object)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3302)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3441)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7405)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.sumup.merchant.reader.ReaderModuleCoreState.inject(java.lang.Object)' on a null object reference
        at com.sumup.merchant.reader.identitylib.ui.activities.LoginActivity.onCreate(SourceFile:247)
        at android.app.Activity.performCreate(Activity.java:7873)
        at android.app.Activity.performCreate(Activity.java:7862)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3277)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3441) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7405) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

**Comment by rivella50** [comment]
@milenpav Did you ever find a solution for this problem?
