### ISSUE TITLE
Crash on some device with latest SDK

### ISSUE THREAD

**Issue by claudiopizzillo** [sumup/sumup-android-sdk#164]
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{it.kefaonline.scontrinoeasy/com.sumup.merchant.reader.identitylib.ui.activities.LoginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.sumup.merchant.reader.ReaderModuleCoreState.inject(java.lang.Object)' on a null object reference

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.sumup.merchant.reader.ReaderModuleCoreState.inject(java.lang.Object)' on a null object reference
       at com.sumup.merchant.reader.identitylib.ui.activities.LoginActivity.onCreate(SourceFile:247)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by fred4o** [comment]
to more device when open loginActivity

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.sumup.merchant.reader.ReaderModuleCoreState.get(java.lang.Class)' on a null object reference
       at com.sumup.merchant.reader.api.SumUpAPI.getIdentityModel(SourceFile:89)
       at com.sumup.merchant.reader.api.SumUpAPI.isLoggedIn(SourceFile:96)
       at bg.hippotaxi.driver.ui.SettingsFragment.onCreateView(SettingsFragment.java:81)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
       at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1830)
       at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:303)
       at bg.hippotaxi.driver.ui.MainActivity.addFragment(MainActivity.java:1970)
       at bg.hippotaxi.driver.ui.MainActivity.openSettings(MainActivity.java:1494)
       at bg.hippotaxi.driver.ui.MainActivity_ViewBinding$2.doClick(MainActivity_ViewBinding.java:66)
       at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:26)
       at android.view.View.performClick(View.java:6659)
       at android.view.View.performClickInternal(View.java:6631)
       at android.view.View.access$3100(View.java:790)
       at android.view.View$PerformClick.run(View.java:26187)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by fred4o** [comment]
did you call             SumUpState.init(this);
before?

**Comment by claudiopizzillo** [comment]
Yes. I think this are rooted devices. Can be a problem?

**Comment by rivella50** [comment]
@claudiopizzillo Did you ever find a solution here?
I have the exact same crash on certain Android devices.

**Comment by claudiopizzillo** [comment]
I abandoned sumup due the unusable sdk 4.0.x  for duplicate dependecies on build not fixed.

**Comment by vigneshsankar07** [comment]
Copy that lib.. manifest of <activity/> & <services/> & paste your project manifest file. 

That will be worked on success. (y).

**Comment by leila-sumup** [comment]
Hello, thanks for taking the time to report this, and apologies the slow follow-up on our end.

Since this is a few years old, we'd like to check if it's still relevant before moving forward.
Could you confirm:
-Are you still seeing this with the latest version of the SDK?
-If so, what mobile device do you use, and what Android version?
-Is there any way to reliably reproduce it or trends in occurrence?

If it's no longer an issue, we'll go ahead and close this out, but we'll keep the underlying concern noted for future improvements.

Thanks again for your patience.

**Comment by leila-sumup** [comment]
Closing this one as it seems no longer relevant and no recent follow up.

If this issue still persists with the latest SDK, please re-open the issue and provide steps to reproduce and information on your setup (card reader used, mobile device manufacturer and model) so that we can look into it!
