### ISSUE TITLE
Application Crashlytics in com.sumup.merchant.reader.helpers.BluetoothHelper.disableBluetooth 

### ISSUE THREAD

**Issue by radumaerza** [sumup/sumup-android-sdk#172]
![image](https://user-images.githubusercontent.com/44721909/147933574-2cf95c8e-f94c-461d-8094-1829491c3150.png)

```java
Fatal Exception: java.lang.SecurityException
Permission Denial: broadcast from android asks to run as user 0 but is calling from uid u10a271; this requires android.permission.INTERACT_ACROSS_USERS_FULL or android.permission.INTERACT_ACROSS_USERS
```

```java
android.os.Parcel.createExceptionOrNull (Parcel.java:2373)
android.os.Parcel.createException (Parcel.java:2357)
android.os.Parcel.readException (Parcel.java:2340)
android.os.Parcel.readException (Parcel.java:2282)
android.bluetooth.IBluetoothManager$Stub$Proxy.disable (IBluetoothManager.java:691)
android.bluetooth.BluetoothAdapter.disable (BluetoothAdapter.java:1411)
com.sumup.merchant.reader.helpers.BluetoothHelper.disableBluetooth (SourceFile:10)
com.sumup.merchant.reader.helpers.BluetoothStateChangeHelper.toggleBluetooth (SourceFile:4)
com.sumup.merchant.reader.troubleshooting.ui.PinPlusBtToggleFragment$1.onClick (SourceFile:10)
android.view.View.performClick (View.java:7461)
android.view.View.performClickInternal (View.java:7438)
android.view.View.access$4000 (View.java:815)
android.view.View$PerformClick.run (View.java:28396)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:223)
android.app.ActivityThread.main (ActivityThread.java:7868)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:592)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:981)
```

```java
Caused by android.os.RemoteException
Remote stack trace: at com.android.server.am.UserController.handleIncomingUser(UserController.java:1940) at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:16442) at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:16398) at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:17218) at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1148)
```

**Comment by leila-sumup** [comment]
Hello, thanks for taking the time to report this, and apologies the slow follow-up on our end.

Since this is a few years old, we'd like to check if it's still relevant before moving forward. Could you confirm:
-Are you still seeing this with the latest version of the SDK?
-If so, what mobile device, and what Android version?
Any steps to reproduce would be helpful.

If it's no longer an issue, we'll go ahead and close this out, but we'll keep the underlying concern noted for future improvements.

Thanks again for your patience.

**Comment by leila-sumup** [comment]
Closing this one as it seems no longer relevant and no recent follow up.

If this issue still persists with the latest SDK, please re-open the issue and provide steps to reproduce and information on your setup (card reader used, mobile device manufacturer and model) so that we can look into it!
