### ISSUE TITLE
App crashes everytime I try to use prepareForCheckout()

### ISSUE THREAD

**Issue by plastik-fasche** [sumup/sumup-android-sdk#176]
Everytime I try to use it I get this message in the debug terminal:

E/AndroidRuntime: FATAL EXCEPTION: Animation Thread
    Process: processing.test.test_android, PID: 1056
    java.lang.IllegalStateException: Must be called from main thread
        at com.sumup.merchant.reader.bluetooth.BaseBtSmartScanner.ensureMainThread(SourceFile:2)
        at com.sumup.merchant.reader.bluetooth.BaseBtSmartScanner.startScan(SourceFile:1)
        at com.sumup.merchant.reader.cardreader.ReaderCoreManager.scanForAirs(SourceFile:14)
        at com.sumup.merchant.reader.cardreader.ReaderCoreManager.detectCardReader(SourceFile:43)
        at com.sumup.merchant.reader.cardreader.ReaderCoreManager.wakePinPlusDevice(SourceFile:8)
        at com.sumup.merchant.reader.cardreader.ReaderCoreManager.cleanAndWakePinPlusDevice(SourceFile:17)
        at com.sumup.merchant.reader.api.SumUpAPI.prepareForCheckout(SourceFile:7)
        at processing.test.test_android.MainActivity.prepare(MainActivity.java:68)
        at processing.test.test_android.test_android.mousePressed(test_android.java:52)
        at processing.core.PApplet.mousePressed(PApplet.java:2389)
        at processing.core.PApplet.handleMouseEvent(PApplet.java:2172)
        at processing.core.PApplet.dequeueEvents(PApplet.java:2091)
        at processing.core.PApplet.handleDraw(PApplet.java:1905)
        at processing.core.PSurfaceNone.callDraw(PSurfaceNone.java:478)
        at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:518)

I tried calling the function for MainActivity but it still doesn't work

**Comment by leila-sumup** [comment]
Hello, thanks for taking the time to report this, and apologies the slow follow-up on our end.

Since this is a few years old, we'd like to check if it's still relevant before moving forward. 
Could you confirm:
-Which card reader are you using?
-Are you still seeing this with the latest version of the SDK?
-If so, what mobile device do you use, and what Android version?
Any steps to reproduce would be helpful.

If it's no longer an issue, we'll go ahead and close this out, but we'll keep the underlying concern noted for future improvements.

Thanks again for your patience.

**Comment by leila-sumup** [comment]
Closing this one as it seems no longer relevant and no recent follow up.

If this issue still persists with the latest SDK, please re-open the issue and provide steps to reproduce and information on your setup (card reader used, mobile device manufacturer and model) so that we can look into it!
