### ISSUE TITLE
RuntimeException TransactionTooLargeException exception is crashing app.

### ISSUE THREAD

**Issue by dp-singh** [sumup/sumup-android-sdk#178]
We have had a crash report on firebase  `This issue has 1107 fatal events affecting 219 users`

```
Caused by android.os.TransactionTooLargeException: data parcel size 605268 bytes
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:1154)
       at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:3992)
       at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6865)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Happening in `CardReaderPaymentAPIDrivenPageActivity`.

This generally happens when you passing large amount of data through intent. Reference to [SO](https://stackoverflow.com/questions/11451393/what-to-do-on-transactiontoolargeexception)

SDK version: Release 3.4.0

**Comment by leila-sumup** [comment]
Hello, thanks for taking the time to report this, and apologies the slow follow-up on our end.

Since this is a few years old, we'd like to check if it's still relevant before moving forward.
Could you confirm:
-Are you still seeing this with the latest version of the SDK?
-If so, what mobile device do you use, and what Android version?
-Is there any way to reliably reproduce it or trends in occurrence?

If it's no longer an issue, we'll go ahead and close this out, but we'll keep the underlying concern noted for future improvements.

Thanks again for your patience.

**Comment by leila-sumup** [comment]
Closing this one as it seems no longer relevant and no recent follow up.

If this issue still persists with the latest SDK (7.0), please re-open the issue and provide steps to reproduce and information on your setup (card reader used, mobile device manufacturer and model) so that we can look into it!
