### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException Cannot retrieve SumUp reader type

### ISSUE THREAD

**Issue by radumaerza** [sumup/sumup-android-sdk#180]
Fatal Exception: java.lang.IllegalStateException: Cannot retrieve SumUp reader type
       at com.sumup.merchant.reader.bluetooth.ScannedCardReaderDevice.readerTypeForUUID(SourceFile:29)
       at com.sumup.merchant.reader.bluetooth.ScannedCardReaderDevice.<init>(SourceFile:6)
       at com.sumup.merchant.reader.bluetooth.BaseBtSmartScanner.onNewResult(SourceFile:3)
       at com.sumup.merchant.reader.bluetooth.ModernBtSmartScanner$1.onScanResult(SourceFile:6)
       at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:508)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7868)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

**Comment by HeyPouya** [comment]
Hi @radumaerza, Can you please let us know which reader are you using?

**Comment by radumaerza** [comment]
SumUp Air. But I mean the issue is four years old.

**Comment by HeyPouya** [comment]
@radumaerza Thanks for the update. Are you still seeing this issue with the latest SDK version?

**Comment by leila-sumup** [comment]
Hello @radumaerza  apologies the slow follow-up on our end.

Since, as you pointed out, this is a few years old, we'd like to check if it's still relevant before moving forward.
Could you confirm:
-Are you still seeing this with the latest version of the SDK?
-If so, what mobile device do you use, and what Android version?
-Is there any way to reliably reproduce it or trends in occurrence?

If it's no longer an issue, we'll go ahead and close this out, but we'll keep the underlying concern noted for future improvements.

Thanks again for your patience.

**Comment by radumaerza** [comment]
You can close this for now - I would reopen a new one if I will find this in future releases.

**Comment by leila-sumup** [comment]
@radumaerza Thanks for letting us know! Closing now then :)
