### ISSUE TITLE
BLUETOOTH_SCAN permission missing

### ISSUE THREAD

**Issue by towsif-hossain** [sumup/sumup-android-sdk#189]
I am getting following crash on Android 12 devices while bluetooth scan screen is open to  take payments.

```
Fatal Exception: java.lang.SecurityException: Need android.permission.BLUETOOTH_SCAN permission for AttributionSource { uid = 10258, packageName = com.example.app, attributionTag = null, token = android.os.BinderProxy@1885f77, next = null }: GattService registerScanner
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
       at android.os.Parcel.createException(Parcel.java:2421)
       at android.os.Parcel.readException(Parcel.java:2404)
       at android.os.Parcel.readException(Parcel.java:2346)
       at android.bluetooth.IBluetoothGatt$Stub$Proxy.registerScanner(IBluetoothGatt.java:1886)
       at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.startRegistration(BluetoothLeScanner.java:519)
       at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:305)
       at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:161)
       at com.sumup.merchant.reader.bluetooth.ModernBtSmartScanner.start(SourceFile:78)
       at com.sumup.merchant.reader.bluetooth.BaseBtSmartScanner.handleMessage(SourceFile:12)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

SDK version 3.4.0

**Comment by spectrumIG** [comment]
Welcome to the club. This issue is here since at least 1-1,5 year and no one, NO ONE has at least taken the time to give an answer. The sdk is stuck with targetSdk 29. That's the reason.

**Comment by OliverHoffmann** [comment]
Hello, I get the same issue. Is it still not fixed?

What can I do to get the SDK to work? Or to help in fixing this issue?

Thank you :)

**Comment by leila-sumup** [comment]
Hello, thanks for taking the time to report this, and apologies the slow follow-up on our end.

Since this is a few years old, we'd like to check if it's still relevant before moving forward.
Could you confirm:
-Are you still seeing this with the latest version of the SDK? (we've just released v7.0, which has significant bluetooth improvements over older versions)
-If so, what mobile device do you use, and what Android version?
-Is there any way to reliably reproduce it or trends in occurrence?

If it's no longer an issue, we'll go ahead and close this out, but we'll keep the underlying concern noted for future improvements.

Thanks again for your patience.

**Comment by spectrumIG** [comment]
@leila-sumup Hi, I really can't answer you because due to some business moves we are not using sumup anymore in general   inside the company . In the app I made a little fix for this so I have no traces of that either.  Sorry.

**Comment by leila-sumup** [comment]
Hi @spectrumIG , thanks for letting me know. I'll close this one for now then. 

For others, if this issue comes up again, please reopen the ticket with the above requested context.
