### ISSUE TITLE
SDK 4.0.0 upgrade

### ISSUE THREAD

**Issue by towsif-hossain** [sumup/sumup-android-sdk#193]
We have recently update the SDK to `4.0.0` and this what we get when transaction is SUCCESS. This is causing a huge outrage in out application. Please let us know what wrong here?

```
Fatal Exception: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter text
       at com.sumup.designlib.circuitui.components.SumUpTextField.setText(:2)
       at com.sumup.merchant.reader.ui.fragments.TxSuccessFragment$1.setPhoneNumber(SourceFile:1)
       at com.sumup.merchant.reader.presenter.ReceiptPresenter.populateFieldsFromApi(SourceFile:4)
       at com.sumup.merchant.reader.ui.fragments.TxSuccessFragment.onActivityCreated(SourceFile:31)
       at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2996)
       at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:580)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
       at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by zaid-abdullah** [comment]
This was potentially a bug in one of the internal libraries, which should have been fixed, as we are not able to reproduce the issue.
Please update to the latest version 6.0.0.
Please let us know if you are still experiencing this issue. I just wanted to let you know that I'm closing this for now.
