### ISSUE TITLE
Gradle not generated correctly sumup/merchant/R.java file : missing entries after gradle sync

### ISSUE THREAD

**Issue by welovehangers** [sumup/sumup-android-sdk#22]
I need your help !

I have a fatal error when SumUp try to launch login activity. Please see the error log below. I found in the _Generated folder_ the _R.java_ file and this field is missing. I used Android Studio and I have installed a plugin to decompile LoginActivity class. Several ids are missing (highlighted with ** ... ** marker). No LoginActivity class in my project. 

```
private void setUpViews() {
        this.mAutoLogInContainer = this.findViewById(id.**container_auto_login**);
        this.mLoginContainer = this.findViewById(id.**container_login**);
        this.mAutoEmailView = (TextView)this.findViewById(id.**tv_auto_email**);
        this.mEmailField = (AutoCompleteTextView)this.findViewById(id.email);
        this.mEmailField.setAdapter(LoginUtils.getEmailAddressAdapter(this));
        this.mEmailWrapper = (TextInputLayout)this.findViewById(id.**wrapper_email**);
        this.mPasswordField = (EditText)this.findViewById(id.password);
        this.mPasswordField.setImeActionLabel(this.getString(string.sumup_login_btn_log_in), 2);
        this.mPasswordField.setOnEditorActionListener(new OnEditorActionListener() {
            public boolean onEditorAction(TextView v, int actionId, KeyEvent event) {
                if(actionId == 2 || event != null && event.getKeyCode() == 66 && event.getAction() == 1) {
                    LoginActivity.this.doManualLogIn();
                }

                return false;
            }
        });
        this.mPasswordWrapper = (TextInputLayout)this.findViewById(id.**wrapper_password**);
        final Typeface var1 = Typeface.create("sans-serif-light", 0);
        this.mPasswordField.setTypeface(var1);
        this.mPasswordField.addTextChangedListener(new TextWatcher() {
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {
                if(s.length() == 0 && after > 0) {
                    LoginActivity.this.mPasswordField.setTypeface(Typeface.MONOSPACE);
                }

            }

            public void afterTextChanged(Editable s) {
                if(s.length() == 0) {
                    LoginActivity.this.mPasswordField.setTypeface(var1);
                    LoginActivity.this.mPasswordWrapper.setPasswordVisibilityToggleEnabled(true);
                }

            }

            public void onTextChanged(CharSequence s, int start, int before, int count) {
            }
        });
        this.mLogInButton = (Button)this.findViewById(id.**btn_log_in**);
        this.mLogInSpinnerContainer = this.findViewById(id.**login_spinner**);
        this.mForgotPasswordView = (TextView)this.findViewById(id.**btn_forgot_password**);
    }
```

When I play with Sample SumUp Android SDK, your file contains this field. I follow all steps indicated in your tutorial. 

> gradle : 2.3.0
> 
> compileSdkVersion 25
>     buildToolsVersion "25.0.2"
>     defaultConfig {
>         applicationId "****.h_mvp_2"
>         minSdkVersion 24
>         targetSdkVersion 25
>         versionCode 1
>         versionName "1.0"
>     }

What's wrong ?

```
FATAL EXCEPTION: main
                                                                      Process: ****.h_mvp_2, PID: 1214
                                                                      java.lang.NoSuchFieldError: No static field container_auto_login of type I in class Lcom/sumup/merchant/R$id; or its superclasses (declaration of 'com.sumup.merchant.R$id' appears in /data/app/io.hangers.www.h_mvp_2-2/split_lib_slice_8_apk.apk)
                                                                          at com.sumup.merchant.ui.Activities.LoginActivity.setUpViews(SourceFile:318)
                                                                          at com.sumup.merchant.ui.Activities.LoginActivity.onCreate(SourceFile:168)
                                                                          at android.app.Activity.performCreate(Activity.java:6662)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                          at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by welovehangers** [comment]
I found my error thanks to issue : Problem with SDK integration #14
I have a layout called : activity_login.xml

**Comment by vfoixcable** [comment]
You re not the first one to bring that (but the first one publicly) 
Indeed, it is a known issue from our end and we will fix this by renaming this layout in the next release!
