### ISSUE TITLE
App Crashed on SetupFragment closes when terminal is connected

### ISSUE THREAD

**Issue by milenpav** [sumup/sumup-android-sdk#230]
'com.sumup:merchant-sdk:5.0.2'

 java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams androidx.constraintlayout.widget.Guideline.getLayoutParams()' on a null object reference
                                                                                                    	at com.sumup.merchant.reader.ui.fragments.SetupFragment.setGuidelinePercentage(SourceFile:1)
                                                                                                    	at com.sumup.merchant.reader.ui.fragments.SetupFragment.onCreateView(SourceFile:43)
                                                                                                    	at com.sumup.merchant.reader.ui.fragments.PinPlusSetupFragment.onCreateView(SourceFile:1)
                                                                                                    	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3113)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)

**Comment by milenpav** [comment]
some info here

**Comment by milenpav** [comment]
@julienschmidt @Elemag @Lucien @ultrah 
fix this pleace

**Comment by leila-sumup** [comment]
Hello, thanks for taking the time to report this, and apologies the slow follow-up on our end.

Since this is a few years old, we'd like to check if it's still relevant before moving forward.
Could you confirm:
-Are you still seeing this with the latest version of the SDK?
-If so, what mobile device do you use, and what Android version?
-Is there any way to reliably reproduce it or trends in occurrence?

If it's no longer an issue, we'll go ahead and close this out, but we'll keep the underlying concern noted for future improvements.

Thanks again for your patience.

**Comment by leila-sumup** [comment]
Closing this one as it seems no longer relevant and no recent follow up.

If this issue still persists with the latest SDK (7.0), please re-open the issue and provide steps to reproduce and information on your setup (card reader used, mobile device manufacturer and model) so that we can look into it!
