### ISSUE TITLE
java.lang.NoSuchFieldException: No field mMaxWidth in class Landroid/widget/ImageView;

### ISSUE THREAD

**Issue by whyteH** [sumup/sumup-android-sdk#232]
## Summary
```
Accessing hidden field Landroid/widget/ImageView;->mMaxWidth:I (greylist-max-p, reflection, denied)
No field mMaxWidth in class Landroid/widget/ImageView; (declaration of 'android.widget.ImageView' appears in /system/framework/framework.jar!classes3.dex)
framework/framework.jar!classes3.dex)
  at java.lang.Class.getDeclaredField(Native Method)
  at com.nostra13.universalimageloader.core.imageaware.ImageViewAware.getImageViewFieldValue(ImageViewAware.java:132)
  at com.nostra13.universalimageloader.core.imageaware.ImageViewAware.getWidth(ImageViewAware.java:79)
  at com.nostra13.universalimageloader.utils.ImageSizeUtils.defineTargetSizeForView(ImageSizeUtils.java:54)
  at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:260)
  at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:209)
  at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:316)
  at com.sumup.merchant.reader.ui.fragments.CardReaderPaymentFragment.setUpImageView(SourceFile:15)
  at com.sumup.merchant.reader.ui.fragments.TxFailedFragment.populateUiFromScreenData(SourceFile:3)
  at com.sumup.merchant.reader.ui.fragments.TxFailedFragment.onActivityCreated(SourceFile:6)
  at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3146)
  at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:579)
  at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:264)
  at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1901)
  at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1819)
  at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1762)
  at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
  at android.os.Handler.handleCallback(Handler.java:938)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:223)
  at android.app.ActivityThread.main(ActivityThread.java:7664)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
![image](https://github.com/user-attachments/assets/b857d7e9-ba13-476a-a23e-d2ae608946bf)

## Android version
Android 11

## Impacted devices (Android devices or readers)
Solo Lite
## SDK version
5.0.2

**Comment by HeyPouya** [comment]
Hi @whyteH ,
I’m marking this issue as resolved since it has been fixed in version 7.0.0.
If you’re still experiencing the same problem, please feel free to reopen the issue and let us know.
